# Writing figures and the generated tex. Nothing here decides anything; it only
# formats what the panels and the statistics already computed.

save_fig <- function(plot, name, width, height) {
  ggplot2::ggsave(file.path("figs", "out", paste0(name, ".pdf")), plot,
                  width = width, height = height, units = "in", device = cairo_pdf)
  invisible(NULL)
}

# Signed quantities are set in maths mode. Two reasons: a text hyphen is not a
# minus sign, and TeX is allowed to break a line after one, which puts the digits
# of a negative number on the next line without its sign.
fmt <- function(x, digits = 2) {
  out <- formatC(x, format = "f", digits = digits)
  ifelse(x < 0, paste0("$", out, "$"), out)
}
signed <- function(x, digits = 2) sprintf(paste0("$%+.", digits, "f$"), x)
pct <- function(x, digits = 1) formatC(100 * x, format = "f", digits = digits)
thousands <- function(x) format(x, big.mark = ",", trim = TRUE, scientific = FALSE)

# Probabilities here run many orders of magnitude below the conventional
# threshold, so a fixed number of decimals would print zero. Rendered as a power
# of ten in maths mode rather than as the exponent notation R would give.
sci <- function(x, digits = 1) {
  exponent <- floor(log10(x))
  mantissa <- x / 10^exponent
  sprintf("$%.*f \\times 10^{%d}$", digits, mantissa, as.integer(exponent))
}

# A whole-number ratio reads better as a word than as a numeral: the manuscript
# says "ten times the budget" rather than "10 times". Written here so the
# sentence and the arithmetic behind it cannot come apart.
count_word <- function(n) {
  words <- c("one", "two", "three", "four", "five", "six", "seven", "eight",
             "nine", "ten", "eleven", "twelve")
  if (n >= 1 && n <= length(words)) words[[n]] else as.character(n)
}

macro <- function(name, value) sprintf("\\newcommand{\\%s}{%s}", name, value)

GENERATED_HEADER <- "% Generated by the figure script from hash-bound evidence. Do not hand-edit."

write_generated <- function(lines, name) {
  writeLines(c(GENERATED_HEADER, lines), file.path("tex", name))
  invisible(NULL)
}
